// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDZg8zwDcxvZvJEeFSt0Bp-hmqliUrQqo',
    appId: '1:1054135743627:web:6da5600aece974678dd08e',
    messagingSenderId: '1054135743627',
    projectId: 'interntask-190da',
    authDomain: 'interntask-190da.firebaseapp.com',
    storageBucket: 'interntask-190da.firebasestorage.app',
    measurementId: 'G-HFPRY1VT5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATB4IgUXnJ3J0tgOxMXEWV-x3e4agQoUc',
    appId: '1:1054135743627:android:6c2de5e36beb9eb68dd08e',
    messagingSenderId: '1054135743627',
    projectId: 'interntask-190da',
    storageBucket: 'interntask-190da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCneC5ePhl6VzIHBA-9vs2TnIF4-UjyMgg',
    appId: '1:1054135743627:ios:2f8fc3ee7f8565548dd08e',
    messagingSenderId: '1054135743627',
    projectId: 'interntask-190da',
    storageBucket: 'interntask-190da.firebasestorage.app',
    iosBundleId: 'com.example.tailorapptask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCneC5ePhl6VzIHBA-9vs2TnIF4-UjyMgg',
    appId: '1:1054135743627:ios:2f8fc3ee7f8565548dd08e',
    messagingSenderId: '1054135743627',
    projectId: 'interntask-190da',
    storageBucket: 'interntask-190da.firebasestorage.app',
    iosBundleId: 'com.example.tailorapptask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDZg8zwDcxvZvJEeFSt0Bp-hmqliUrQqo',
    appId: '1:1054135743627:web:b34f0886ddb72d088dd08e',
    messagingSenderId: '1054135743627',
    projectId: 'interntask-190da',
    authDomain: 'interntask-190da.firebaseapp.com',
    storageBucket: 'interntask-190da.firebasestorage.app',
    measurementId: 'G-G1G1WF3PXK',
  );
}
// Platform  Firebase App Id
// web       1:1054135743627:web:6da5600aece974678dd08e
// android   1:1054135743627:android:6c2de5e36beb9eb68dd08e
// ios       1:1054135743627:ios:2f8fc3ee7f8565548dd08e
// macos     1:1054135743627:ios:2f8fc3ee7f8565548dd08e
// windows   1:1054135743627:web:b34f0886ddb72d088dd08e